# Generated by Django 5.0.6 on 2024-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('query', models.TextField()),
                ('sim1', models.FloatField()),
                ('sim2', models.FloatField()),
                ('sim3', models.FloatField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
