# Generated by Django 5.0.6 on 2024-05-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChromaData',
        ),
        migrations.DeleteModel(
            name='history',
        ),
    ]
