# Generated by Django 5.0.6 on 2024-06-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('query', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
