# Generated by Django 5.0.6 on 2024-06-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfchatgpt', '0002_chromadb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=100)),
                ('title', models.TextField(blank=True, null=True)),
                ('qa_id', models.ForeignKey(db_column='qa_id', on_delete=django.db.models.deletion.CASCADE, to='selfchatgpt.querylog')),
            ],
        ),
    ]
