# Generated by Django 5.0.6 on 2024-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfchatgpt', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
