# Generated by Django 5.0.6 on 2024-06-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfchatgpt', '0004_topic_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromadb',
            name='category',
            field=models.CharField(default='None', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='chromadb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
